modLoader = "javafml"
loaderVersion = "[48,)"
issueTrackerURL = "https://github.com/CreeperHost/Chickens/issues"
license = "MIT License"

[[mods]]
modId = "chickens"
version = "${version}"
displayName = "Chickens"
authors = "CreeperHost"
description = '''
'''
logoFile = "logo.png"

[[dependencies.chickens]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chickens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.chickens]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.chickens]]
modId = "polylib"
mandatory = true
versionRange = "[2002.0.3,)"
ordering = "AFTER"
side = "BOTH"
