modLoader = "javafml"
loaderVersion = "[46,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "chickens"
version = "${version}"
displayName = "Chickens"
authors = "CreeperHost"
description = '''
'''
#logoFile = ""

[[dependencies.chickens]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chickens]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.chickens]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.chickens]]
modId = "polylib"
mandatory = true
versionRange = "[1200.0.3,)"
ordering = "AFTER"
side = "BOTH"
