name: Java CI

on:
  push:
    branches: [ release/1.21 ]
  workflow_dispatch:
    inputs:
      norelease:
        description: 'Do not publish'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        env:
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publishUnified --stacktrace --no-daemon
